CREATE DATABASE CPSC332;

USE CPSC332;


CREATE TABLE TEST.TEST (ID INT NOT NULL);

SELECT * FROM INFORMATION_SCHEMA.TABLES;

SELECT * FROM INFORMATION_SCHEMA.COLUMNS;

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT SSN, DNO FROM EMPLOYEE;